<?php include './header.phtml'; ?>
        <h1>Ajouter un Film</h1>
    <form action="./ajoutFilm.php" method="post">
        <div>
            <label for="titre">Titre : </label>
            <input type="text" name="titre" id="titre" />
        </div>
        <div>
            <label for="img">Image : </label>
            <input type="text" name="img" id="img" />
        </div>
      
        <div>
            <label for="desc">Description : </label>
            <textarea name="desc" id="desc" cols="30" rows="10"></textarea>
        </div>
        <div>
            <label for="date">Date de sortie : </label>
            <input type="date" name="date" id="date" />
        </div>
        <div>
            <div></div>
            <input type="submit" value="Ajouter">
            <div></div>
        </div>
    </form>

    <?php
        if($ret!="")
        {
            echo '<h2>'.$ret.'</h2>';
        }
    ?>
<?php include './footer.phtml'; ?>